---
node.name: es02
network.host: 0.0.0.0
discovery.seed_hosts: es01,es03
cluster.initial_master_nodes: es01,es02,es03
bootstrap.memory_lock: true
xpack.security.enabled: false
xpack.license.self_generated.type: basic
xpack.security.http.ssl.enabled: false
